apiVersion: v1
kind: Service
metadata:
  name: service-release
  namespace: release
spec:
  type: LoadBalancer
  selector:
    app: micros
  ports:
    - name: core
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: front
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dbapi
      protocol: TCP
      port: 8000
      targetPort: 8000